# Generated by Django 2.1.5 on 2019-03-04 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import labs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('variant', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='variant')),
                ('deadline', models.DateField(default=datetime.datetime(2019, 3, 5, 19, 59, 35, 656523, tzinfo=utc), verbose_name='deadline')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=labs.models.task_upload_path, verbose_name='attachment')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
    ]
