# Generated by Django 2.1.7 on 2019-03-07 14:41

from django.db import migrations


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    apps.get_model("labs", "Task").objects.using(db_alias).all().delete()
    apps.get_model("labs", "StudyClass").objects.using(db_alias).all().delete()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_studyclass'),
    ]

    operations = [
        migrations.RunPython(
            code=forwards_func,
            reverse_code=reverse_func,
        ),
    ]
