# Generated by Django 2.1.7 on 2019-03-07 10:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import labs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_dbflush'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ('name',), 'verbose_name': 'discipline', 'verbose_name_plural': 'disciplines'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('number',), 'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='studyclass',
            options={'ordering': ('discipline', 'group'), 'verbose_name': 'study class', 'verbose_name_plural': 'study classes'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('study_class', 'order'), 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AddField(
            model_name='studyclass',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='study_classes', related_query_name='study_class', to='labs.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='task number in study class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='study_class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', related_query_name='task', to='labs.StudyClass', verbose_name='study class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=0, max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyclass',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_classes', related_query_name='study_class', to='labs.Discipline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[labs.validators.DateValidator()], verbose_name='deadline'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='variant',
        ),
        migrations.AddField(
            model_name='task',
            name='variant',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='variant'),
        ),
        migrations.RemoveField(
            model_name='studyclass',
            name='task',
        ),
        migrations.AlterUniqueTogether(
            name='studyclass',
            unique_together={('discipline', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('study_class', 'order')},
        ),
    ]
