# Generated by Django 2.1.5 on 2019-03-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_auto_20190327_1737'),
        ('labs', '0006_auto_20190307_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField(default=True, verbose_name='attendance')),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'attendances',
                'ordering': ('lesson', 'student'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'ordering': ('study_class', 'date'),
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, max_length=128, null=True, verbose_name='mark')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', related_query_name='mark', to='labs.Lesson', verbose_name='lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', related_query_name='mark', to='custom_auth.Student', verbose_name='student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', related_query_name='mark', to='labs.Task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'mark',
                'verbose_name_plural': 'marks',
                'ordering': ('lesson', 'task', 'student'),
            },
        ),
        migrations.AddField(
            model_name='studyclass',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='study_classes', related_query_name='study_class', to='custom_auth.Teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='study_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', related_query_name='lesson', to='labs.StudyClass', verbose_name='study class'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', related_query_name='attendance', to='labs.Lesson', verbose_name='lesson'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', related_query_name='attendance', to='custom_auth.Student', verbose_name='student'),
        ),
    ]
