# Generated by Django 2.2 on 2019-05-14 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0008_auto_20190413_1746'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0007_auto_20190327_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='variant',
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'task')},
        ),
        migrations.CreateModel(
            name='TaskVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.TextField(blank=True, null=True, verbose_name='Variant')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='variants',
            field=models.ManyToManyField(related_name='variants', related_query_name='variant', through='labs.TaskVariant', to=settings.AUTH_USER_MODEL),
        ),
    ]
