# Generated by Django 2.1.5 on 2019-03-23 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_init_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_studying',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='year of study'),
        ),
    ]
