# Generated by Django 2.1.5 on 2019-03-24 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_auto_20190323_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Student card number of a student or surname and initials of a teacher.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(regex='^(([A-Z][a-z]+(-[A-Z][a-z]+)?[A-Z]{2})|\\d{7})$')], verbose_name='username'),
        ),
    ]
