# Generated by Django 2.1.5 on 2019-03-27 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='First name of a student or of a teacher.', max_length=15, validators=[django.core.validators.RegexValidator(regex='[A-ZА-ЯЁ][a-zа-яё]+(-[A-ZА-ЯЁ][a-zа-яё]+)?')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(help_text='Patronymic name of a student or of a teacher.', max_length=20, validators=[django.core.validators.RegexValidator(regex='[A-ZА-ЯЁ][a-zа-яё]+(-[A-ZА-ЯЁ][a-zа-яё]+)?')], verbose_name='patronymic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(help_text='Surname of a student or of a teacher.', max_length=25, validators=[django.core.validators.RegexValidator(regex='[A-ZА-ЯЁ][a-zа-яё]+(-[A-ZА-ЯЁ][a-zа-яё]+)?')], verbose_name='surname'),
        ),
    ]
