# Generated by Django 2.1.5 on 2019-04-13 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_auto_20190327_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='auditorium',
            field=models.CharField(help_text='Required. Format: auditorium-campus.', max_length=6, validators=[django.core.validators.RegexValidator(regex='^\\d{3}[a-z]?-[1-9]$')], verbose_name='auditorium'),
        ),
    ]
