# Generated by Django 2.2 on 2019-04-18 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_default(apps, scheme):
    Message = apps.get_model('chat', 'Message')
    if Message.objects.exists():
        ChatMembership = apps.get_model('chat', 'ChatMembership')
        ChatGroup = apps.get_model('chat', 'ChatGroup')
        User = apps.get_model('custom_auth', 'User')

        ChatMembership.objects.get_or_create(
            id=0,
            group=ChatGroup.objects.get_or_create(id=0)[0],
            member=User.objects.get_or_create(id=0)[0]
        )


def unapply_creation(apps, scheme):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='to_user',
        ),
        migrations.CreateModel(
            name='ChatMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_action', models.DateTimeField(blank=True, default=None, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.ChatGroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='users',
            field=models.ManyToManyField(related_name='chats', related_query_name='chat', through='chat.ChatMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(create_default, unapply_creation),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='messages', related_query_name='message', to='chat.ChatMembership'),
            preserve_default=False,
        ),
    ]
